[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ag-ui-adk>=0.4.1",
    "fastapi>=0.123.10",
    "google-adk>=1.22.1",
    "uvicorn>=0.40.0",
]
